name: CI/CD Frontend - Innovatech
on:
  push:
    branches:
      - main
    paths:
      - "front_despacho/**"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push image to ECR
        run: |
          docker build -t 863069581230.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest ./front_despacho
          docker push 863069581230.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest

      - name: Notificar despliegue exitoso
        run: echo "Imagen subida a ECR exitosamente. Desplegar manualmente en EC2."
